language: objective-c
osx_image: xcode8.3
rvm:
  - 2.3.0
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - brew outdated swiftlint || brew upgrade swiftlint
before_script:
  - carthage bootstrap --platform iOS --no-use-binaries
script:
- ./Scripts/travis-build-test.sh
after_success:
- bundle exec slather coverage --coveralls ContentfulPersistence.xcodeproj
- pod lib lint ContentfulPersistenceSwift.podspec

